name: quick_invoice
description: "A base app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_keyboard_visibility: 6.0.0
  flutter_screenutil: 5.9.3
  smooth_page_indicator: 2.0.1
  in_app_review: 2.0.11
  uuid: 4.5.2
  package_info_plus: 9.0.0
  share_plus: 12.0.1
  url_launcher: 6.3.2
  path_provider: 2.1.5
  image_picker: 1.2.1
  apphud_helper:
    git:
      url: https://github.com/AppEmpireSwift/apphud_helper.git
      ref: 0.6.1
  device_preview_plus: 2.5.6
  drift: 2.30.1
  drift_flutter: 0.2.8
  pdf: 3.11.3
  pdfx: 2.9.2
  intl: 0.20.2
  shared_preferences: 2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.10.5
  flutter_gen_runner: 5.12.0
  drift_dev: 2.30.1
  flutter_native_splash: 2.4.7
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/premium/
    - assets/fonts/
